### ISSUE TITLE
Not able to open Jupyter Notebook

### ISSUE THREAD

**Issue by srikantak** [vishnumadhu365/oneapi-devsummit-sea-2023#1]
This is realted to oneAPI workshop-

I am at the section "Getting started on AI workshop"

Completed Step-5
I am getting Jupyter notebook link as
 http://10.10.10.1:8888/tree?token=acb1d96b8773d0e87bfe805b4e903f24b0893af77f3fb215
 http://127.0.0.1:8888/tree?token=acb1d96b8773d0e87bfe805b4e903f24b0893af77f3fb215

Stuck at step 6

Note sure - what will be the right command for
	ssh -L port-number:ip-address:portnumber myidc

What is teh vlaue of myidc?

Regards,
Srikanta
srikantak1@gmail.com
9790719925

**Comment by srikantak** [comment]
some more input -

After the command - ssh -L 8888:10.10.10.1:8888 idc-beta-batch-head-node I am getting below error --

u107679@idc-beta-batch-head-node [/home/u107679]$ ssh -L 8888:10.10.10.1:8888 idc-beta-batch-head-node
The authenticity of host 'idc-beta-batch-head-node (10.10.10.1)' can't be established.
ED25519 key fingerprint is SHA256:Eu6daZINdeumfJ+m3MZfJvevJXKv1uj1GmhPGerq/1g.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Failed to add the host to the list of known hosts (/home/u107679/.ssh/known_hosts).
u107679@idc-beta-batch-head-node: Permission denied (publickey).
u107679@idc-beta-batch-head-node [/home/u107679]$

**Comment by vishnumadhu365** [comment]
@srikantak myidc is the hostname that was used by default in the .ssh/config file that was created. If you have changed it to something else, then replace myidc with the host entry in your config file. Hope this helps. Also I have updated the repo readme with a video recording of the steps involved, take a look and see if it helps. Let me know if you still face the issue, will be happy to help

**Comment by srikantak** [comment]
Dear Vishnumadhu,

Thanks a ton for your reply. Now I am facing another problem.
While creating $HOME/.ssh/config , I discovered I don't have write access.
Following error I am getting - 
"config" E212: Can't open file for writing

Also I tried changing the permission of .ssh it have me this error - " chmod: changing permissions of '.ssh': Operation not permitted"

Could you please talk to the administrator and arrange the required permission?


Regards,
Srikanta

**Comment by vishnumadhu365** [comment]
Hey Srikanta

Please note that the $HOME/.ssh/config entry should be on your local
system/laptop and not on the Intel Developer Cloud. Apologies if the IDC
setup guide wasn't clear enough, will look into getting it updated.

Regards
Vishnu

**Comment by srikantak** [comment]
Dear VishnuMadhu,
Could you please share the Video link or URL

Rgd
Srikanta

**Comment by vishnumadhu365** [comment]
@srikantak Video recording [here](https://youtu.be/mN_49JgjY-I).

**Comment by srikantak** [comment]
Thanks VishnuMadhu, finally I am able to open Jupyter Notebook and started experimenting. So this thread is closed.

**Comment by srikantak** [comment]
Thanks VishnuMadhu, finally I am able to open Jupyter Notebook and started experimenting. So this thread is closed.

**Comment by vishnumadhu365** [comment]
Thanks for the confirmation! Feel free to reach out if you have any further
comments or queries.
