### ISSUE TITLE
Password is required

### ISSUE THREAD

**Issue by srikantak** [vishnumadhu365/oneapi-devsummit-sea-2023#2]
[sudo] password for u107679: 

Please let me know what is the password here.

srikantak1@gmail.com

**Comment by vishnumadhu365** [comment]
@srikantak for the schedule/batch access of Intel Developer Cloud, your user will not have sudo access. The recommended way to install packages is using conda or pip. Are you looking at installing some packages not available in anaconda channels ?, lets us know

**Comment by vishnumadhu365** [comment]
@srikantak I assume this is not an issue any longer. Can we go ahead and close this too ?

**Comment by vishnumadhu365** [comment]
Closing on inactivity, feel free to re-open if the issue still exist
